### ISSUE TITLE
Missing Step Context Variable.

### ISSUE THREAD

**Issue by victorursan** [CloudSlang/score-content-sdk#6]
If you want to set a **Variable** for a **Step Session Context** and to make it _private_ (only accessible from that step), there is no simple way to do that. 

For example, if you want to make a _list iterator_ that returns _each element_, you need a **variable** for the **Step Session Context**  that keeps track of the **index** for the current returned element.

In **AFL**, there is **StepSerializableSessionObject**.

**Comment by meshipeer** [comment]
we had few discussions in the past - and we wanted to keep our SDK minimal and simple,
can you please explain the exact requirement?

**Comment by lrevnic** [comment]
Discussing with @victorursan we've decided to use CloudSlang for construct for iterations. We can clone this ER for now.
